apiVersion: v1
kind: Service
metadata:
  name: reporting
  namespace: apps
spec:
  ports:
    - port: 8002
  selector:
    app: reporting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: apps
spec:
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: tempsafe-reporting:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres.data.svc.cluster.local:5432/tempsafe"
