apiVersion: v1
kind: Service
metadata:
  name: shipment
  namespace: apps
spec:
  ports:
    - port: 8000
  selector:
    app: shipment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: shipment
  template:
    metadata:
      labels:
        app: shipment
    spec:
      containers:
        - name: shipment
          image: tempsafe-shipment:latest
          imagePullPolicy: IfNotPresent
          command: ["uvicorn", "shipment-1:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres.data.svc.cluster.local:5432/tempsafe"
          ports:
            - containerPort: 8000
